# Generated by Django 4.2.7 on 2025-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrimeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fr", models.CharField(max_length=255)),
                ("name_wo", models.CharField(max_length=255)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_wo", models.TextField(blank=True, null=True)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("icon", models.CharField(default="AlertTriangle", max_length=50)),
                ("requires_specification", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name_fr"],
            },
        ),
    ]
