# Generated by Django 4.2.7 on 2025-09-30 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaintiff_first_name", models.CharField(max_length=100)),
                ("plaintiff_last_name", models.CharField(max_length=100)),
                ("plaintiff_birth_date", models.DateField()),
                ("plaintiff_birth_place", models.CharField(max_length=100)),
                ("plaintiff_nationality", models.CharField(max_length=50)),
                ("plaintiff_address", models.CharField(max_length=255)),
                ("plaintiff_city", models.CharField(max_length=100)),
                ("plaintiff_postal_code", models.CharField(max_length=20)),
                (
                    "defendant_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defendant_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("defendant_birth_date", models.DateField(blank=True, null=True)),
                (
                    "defendant_birth_place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defendant_nationality",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "defendant_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "defendant_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defendant_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("defendant_unknown", models.BooleanField(default=False)),
                ("facts", models.TextField()),
                ("attachments", models.TextField(blank=True, null=True)),
                (
                    "lawyer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lawyer_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("complaint_date", models.DateField(auto_now_add=True)),
                ("complaint_city", models.CharField(max_length=100)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
