# Generated by Django 4.2.7 on 2025-11-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Complaint", "0003_complaintmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="complaintmessage",
            new_name="Complaint_c_complai_9d74d7_idx",
            old_name="Complaint_c_complai_idx",
        ),
        migrations.RenameIndex(
            model_name="complaintmessage",
            new_name="Complaint_c_complai_932dc1_idx",
            old_name="Complaint_c_complai_read_idx",
        ),
    ]
