# Generated by Django 4.2.7 on 2025-12-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        (
            "Complaint",
            "0004_rename_complaint_c_complai_idx_complaint_c_complai_9d74d7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.crimecategory",
            ),
        ),
    ]
